name: CLI - Build and test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - "src/cli/**"
      - .github/workflows/cli-build-test.yaml
  workflow_dispatch:

jobs:
  analyze:
    strategy:
      matrix:
        os: [macos-latest,windows-latest,ubuntu-latest]
    name: Run dotnet build and test
    runs-on: ${{ matrix.os}}
    env:
      DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: false
    steps:
      - name: Enable long paths for git on Windows
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
        with:
          global-json-file: src/cli/global.json

      - name: Build
        working-directory: src/cli
        run: |
          dotnet build -v m

      - name: Test
        working-directory: src/cli
        run: |
          dotnet test -v m
